import 'instrument_model.dart';

enum SynthPresetCategory {
  melody,
  keyboard,
  bass,
  leads,
  drums,
  pads,
  fx,
}

extension SynthPresetCategoryLabel on SynthPresetCategory {
  String get label {
    switch (this) {
      case SynthPresetCategory.melody:
        return 'Melody';
      case SynthPresetCategory.keyboard:
        return 'Keyboard';
      case SynthPresetCategory.bass:
        return 'Bass';
      case SynthPresetCategory.leads:
        return 'Leads';
      case SynthPresetCategory.drums:
        return 'Drums';
      case SynthPresetCategory.pads:
        return 'Pads';
      case SynthPresetCategory.fx:
        return 'FX';
    }
  }
}

class SynthPreset {
  final String name;
  final SynthPresetCategory category;
  final String description;
  final SimpleSynthParams Function() build;

  const SynthPreset({
    required this.name,
    required this.category,
    required this.description,
    required this.build,
  });

  SimpleSynthParams createParams() => build();

  void applyTo(SimpleSynthParams target) {
    final p = build();
    target.wave = p.wave;
    target.detune = p.detune;
    target.cutoff = p.cutoff;
    target.resonance = p.resonance;
    target.filterMode = p.filterMode;
    target.filterAttack = p.filterAttack;
    target.filterDecay = p.filterDecay;
    target.filterSustain = p.filterSustain;
    target.filterRelease = p.filterRelease;
    target.filterEnvAmt = p.filterEnvAmt;
    target.attack = p.attack;
    target.decay = p.decay;
    target.sustain = p.sustain;
    target.release = p.release;
    target.glide = p.glide;
    target.volume = p.volume;
    target.lfoRate = p.lfoRate;
    target.lfoDepth = p.lfoDepth;
    target.lfoTarget = p.lfoTarget;
    target.drive = p.drive;
    target.osc1Gain = p.osc1Gain;
    target.osc2On = p.osc2On;
    target.osc2Wave = p.osc2Wave;
    target.osc2Detune = p.osc2Detune;
    target.osc2Gain = p.osc2Gain;
    target.osc2FmDepth = p.osc2FmDepth;
    target.osc3On = p.osc3On;
    target.osc3Wave = p.osc3Wave;
    target.osc3Detune = p.osc3Detune;
    target.osc3Gain = p.osc3Gain;
    target.osc3FmDepth = p.osc3FmDepth;
  }
}

final List<SynthPreset> kFactorySynthPresets = <SynthPreset>[
  SynthPreset(
    name: 'Default',
    category: SynthPresetCategory.melody,
    description: 'Solid all-round saw starting point.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.0,
      cutoff: 0.78,
      resonance: 0.16,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.18,
      filterSustain: 0.28,
      filterRelease: 0.18,
      filterEnvAmt: 0.40,
      attack: 0.00,
      decay: 0.16,
      sustain: 0.80,
      release: 0.16,
      glide: 0.00,
      volume: 0.92,
      lfoRate: 0.20,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.10,
    ),
  ),
  SynthPreset(
    name: 'Mono Bass',
    category: SynthPresetCategory.melody,
    description: 'Tight low-pass bass for simple lines.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: -0.06,
      cutoff: 0.34,
      resonance: 0.30,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.12,
      filterSustain: 0.10,
      filterRelease: 0.10,
      filterEnvAmt: 0.62,
      attack: 0.00,
      decay: 0.10,
      sustain: 0.84,
      release: 0.10,
      glide: 0.08,
      volume: 0.96,
      lfoRate: 0.16,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.22,
    ),
  ),
  SynthPreset(
    name: 'Deep Bass',
    category: SynthPresetCategory.melody,
    description: 'Rounder, heavier bass with more low-end weight.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: -0.10,
      cutoff: 0.28,
      resonance: 0.18,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.12,
      filterRelease: 0.12,
      filterEnvAmt: 0.48,
      attack: 0.00,
      decay: 0.12,
      sustain: 0.88,
      release: 0.12,
      glide: 0.05,
      volume: 0.98,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.18,
    ),
  ),
  SynthPreset(
    name: 'Solid Lead',
    category: SynthPresetCategory.melody,
    description: 'Straight saw lead that cuts without getting thin.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.01,
      cutoff: 0.72,
      resonance: 0.20,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.24,
      filterRelease: 0.14,
      filterEnvAmt: 0.36,
      attack: 0.00,
      decay: 0.12,
      sustain: 0.78,
      release: 0.14,
      glide: 0.03,
      volume: 0.94,
      lfoRate: 0.18,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.16,
    ),
  ),
  SynthPreset(
    name: 'Pulse Lead',
    category: SynthPresetCategory.melody,
    description: 'Classic pulse-style lead with a bit more bite.',
    build: () => SimpleSynthParams(
      wave: SynthWave.pulse,
      detune: 0.0,
      cutoff: 0.68,
      resonance: 0.26,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.10,
      filterSustain: 0.22,
      filterRelease: 0.12,
      filterEnvAmt: 0.46,
      attack: 0.00,
      decay: 0.10,
      sustain: 0.76,
      release: 0.14,
      glide: 0.00,
      volume: 0.93,
      lfoRate: 0.18,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.18,
    ),
  ),
  SynthPreset(
    name: 'Acid Mono',
    category: SynthPresetCategory.melody,
    description: 'Resonant mono line for sharper acidic phrases.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.0,
      cutoff: 0.40,
      resonance: 0.68,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.04,
      filterRelease: 0.10,
      filterEnvAmt: 0.82,
      attack: 0.00,
      decay: 0.10,
      sustain: 0.76,
      release: 0.10,
      glide: 0.14,
      volume: 0.94,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.30,
    ),
  ),
  SynthPreset(
    name: 'Soft Pluck',
    category: SynthPresetCategory.keyboard,
    description: 'Short pluck for arps and picked parts.',
    build: () => SimpleSynthParams(
      wave: SynthWave.pulse,
      detune: 0.0,
      cutoff: 0.60,
      resonance: 0.24,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.10,
      filterSustain: 0.00,
      filterRelease: 0.08,
      filterEnvAmt: 0.72,
      attack: 0.00,
      decay: 0.10,
      sustain: 0.08,
      release: 0.08,
      glide: 0.00,
      volume: 0.94,
      lfoRate: 0.16,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.12,
    ),
  ),
  SynthPreset(
    name: 'Soft Keys',
    category: SynthPresetCategory.keyboard,
    description: 'Round mellow keys for chords and simple riffs.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: 0.01,
      cutoff: 0.58,
      resonance: 0.14,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.02,
      filterDecay: 0.24,
      filterSustain: 0.30,
      filterRelease: 0.20,
      filterEnvAmt: 0.26,
      attack: 0.02,
      decay: 0.20,
      sustain: 0.70,
      release: 0.20,
      glide: 0.00,
      volume: 0.92,
      lfoRate: 0.14,
      lfoDepth: 0.02,
      lfoTarget: SynthLfoTarget.amp,
      drive: 0.08,
    ),
  ),
  SynthPreset(
    name: 'Bright Pluck',
    category: SynthPresetCategory.keyboard,
    description: 'Sharper pluck for arps and picked rhythmic parts.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: 0.01,
      cutoff: 0.72,
      resonance: 0.28,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.08,
      filterSustain: 0.00,
      filterRelease: 0.06,
      filterEnvAmt: 0.68,
      attack: 0.00,
      decay: 0.08,
      sustain: 0.10,
      release: 0.08,
      glide: 0.00,
      volume: 0.95,
      lfoRate: 0.14,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.amp,
      drive: 0.16,
    ),
  ),
  SynthPreset(
    name: 'Organ',
    category: SynthPresetCategory.keyboard,
    description: 'Simple bright organ for stabs and held chords.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: 0.00,
      cutoff: 0.88,
      resonance: 0.10,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.10,
      filterSustain: 0.84,
      filterRelease: 0.12,
      filterEnvAmt: 0.08,
      attack: 0.00,
      decay: 0.08,
      sustain: 0.92,
      release: 0.10,
      glide: 0.00,
      volume: 0.95,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.amp,
      drive: 0.20,
    ),
  ),
  SynthPreset(
    name: 'Kick',
    category: SynthPresetCategory.drums,
    description: 'Simple synth kick with punch and body.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: -0.78,
      cutoff: 0.42,
      resonance: 0.16,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.08,
      filterSustain: 0.00,
      filterRelease: 0.08,
      filterEnvAmt: 0.34,
      attack: 0.00,
      decay: 0.12,
      sustain: 0.00,
      release: 0.10,
      glide: 0.00,
      volume: 0.98,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.26,
    ),
  ),
  SynthPreset(
    name: 'Snare',
    category: SynthPresetCategory.drums,
    description: 'Noise snare with a short bright crack.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      cutoff: 0.76,
      resonance: 0.32,
      filterMode: SynthFilterMode.bandPass,
      filterAttack: 0.00,
      filterDecay: 0.10,
      filterSustain: 0.00,
      filterRelease: 0.10,
      filterEnvAmt: 0.50,
      attack: 0.00,
      decay: 0.11,
      sustain: 0.00,
      release: 0.10,
      glide: 0.00,
      volume: 0.96,
      lfoRate: 0.14,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.24,
    ),
  ),
  SynthPreset(
    name: 'Hat',
    category: SynthPresetCategory.drums,
    description: 'Short bright hat for simple patterns.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      cutoff: 0.92,
      resonance: 0.14,
      filterMode: SynthFilterMode.highPass,
      filterAttack: 0.00,
      filterDecay: 0.04,
      filterSustain: 0.00,
      filterRelease: 0.04,
      filterEnvAmt: 0.12,
      attack: 0.00,
      decay: 0.05,
      sustain: 0.00,
      release: 0.04,
      glide: 0.00,
      volume: 0.94,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.12,
    ),
  ),
  SynthPreset(
    name: 'Open Hat',
    category: SynthPresetCategory.drums,
    description: 'Longer brighter hat tail for open accents.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      cutoff: 0.94,
      resonance: 0.16,
      filterMode: SynthFilterMode.highPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.00,
      filterRelease: 0.20,
      filterEnvAmt: 0.10,
      attack: 0.00,
      decay: 0.16,
      sustain: 0.00,
      release: 0.22,
      glide: 0.00,
      volume: 0.94,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.10,
    ),
  ),
  SynthPreset(
    name: 'Warm Pad',
    category: SynthPresetCategory.pads,
    description: 'Slow soft pad for sustained harmony.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.03,
      cutoff: 0.52,
      resonance: 0.14,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.18,
      filterDecay: 0.28,
      filterSustain: 0.52,
      filterRelease: 0.40,
      filterEnvAmt: 0.24,
      attack: 0.18,
      decay: 0.30,
      sustain: 0.78,
      release: 0.46,
      glide: 0.00,
      volume: 0.90,
      lfoRate: 0.16,
      lfoDepth: 0.05,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.08,
    ),
  ),
  SynthPreset(
    name: 'Bright Pad',
    category: SynthPresetCategory.pads,
    description: 'Brighter sustaining pad for upper parts.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.02,
      cutoff: 0.70,
      resonance: 0.18,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.14,
      filterDecay: 0.24,
      filterSustain: 0.60,
      filterRelease: 0.42,
      filterEnvAmt: 0.18,
      attack: 0.14,
      decay: 0.24,
      sustain: 0.80,
      release: 0.42,
      glide: 0.00,
      volume: 0.90,
      lfoRate: 0.18,
      lfoDepth: 0.04,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.10,
    ),
  ),

  // ── Bass ─────────────────────────────────────────────────────────────────

  SynthPreset(
    name: 'Sub Bass',
    category: SynthPresetCategory.bass,
    description: 'Deep pure sine sub for pads and low-end support.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: 0.0,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.sine,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.sine,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.28,
      resonance: 0.10,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.20,
      filterSustain: 0.80,
      filterRelease: 0.30,
      filterEnvAmt: 0.12,
      attack: 0.01,
      decay: 0.20,
      sustain: 0.90,
      release: 0.30,
      glide: 0.00,
      volume: 0.96,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.10,
    ),
  ),

  SynthPreset(
    name: 'Acid Bass',
    category: SynthPresetCategory.bass,
    description: 'Squelchy resonant mono bass — classic acid filter stabs.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.0,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.saw,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.saw,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.36,
      resonance: 0.72,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.02,
      filterRelease: 0.10,
      filterEnvAmt: 0.88,
      attack: 0.00,
      decay: 0.12,
      sustain: 0.72,
      release: 0.10,
      glide: 0.12,
      volume: 0.96,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.32,
    ),
  ),

  SynthPreset(
    name: 'FM Bass',
    category: SynthPresetCategory.bass,
    description: 'Punchy FM bass — sine carrier with 2:1 modulator. DX-style thump.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: 0.0,
      osc1Gain: 1.0,
      osc2On: true,
      osc2Wave: SynthWave.sine,
      osc2Detune: 1.0,       // +12 semitones = 2:1 ratio
      osc2Gain: 0.0,         // pure FM modulator
      osc2FmDepth: 0.28,
      osc3On: false,
      osc3Wave: SynthWave.sine,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.40,
      resonance: 0.18,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.12,
      filterSustain: 0.30,
      filterRelease: 0.16,
      filterEnvAmt: 0.50,
      attack: 0.00,
      decay: 0.16,
      sustain: 0.60,
      release: 0.18,
      glide: 0.00,
      volume: 0.96,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.22,
    ),
  ),

  SynthPreset(
    name: 'Growl Bass',
    category: SynthPresetCategory.bass,
    description: 'Fat detuned saw bass with drive — two oscillators for grit.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.01,
      osc1Gain: 0.85,
      osc2On: true,
      osc2Wave: SynthWave.saw,
      osc2Detune: -0.04,     // slightly below unison
      osc2Gain: 0.75,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.saw,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.45,
      resonance: 0.26,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.18,
      filterSustain: 0.40,
      filterRelease: 0.18,
      filterEnvAmt: 0.40,
      attack: 0.00,
      decay: 0.18,
      sustain: 0.78,
      release: 0.18,
      glide: 0.06,
      volume: 0.94,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.38,
    ),
  ),

  SynthPreset(
    name: 'Wobble Bass',
    category: SynthPresetCategory.bass,
    description: 'LFO-filtered saw bass for dubstep-style wobble lines.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.01,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.saw,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.saw,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.30,
      resonance: 0.50,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.20,
      filterSustain: 0.70,
      filterRelease: 0.20,
      filterEnvAmt: 0.30,
      attack: 0.00,
      decay: 0.20,
      sustain: 0.86,
      release: 0.20,
      glide: 0.00,
      volume: 0.94,
      lfoRate: 0.30,
      lfoDepth: 0.55,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.24,
    ),
  ),

  // ── Leads ─────────────────────────────────────────────────────────────────

  SynthPreset(
    name: 'Saw Lead',
    category: SynthPresetCategory.leads,
    description: 'Clean resonant saw lead — workhorse for melodies.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.0,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.saw,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.saw,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.62,
      resonance: 0.22,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.16,
      filterSustain: 0.40,
      filterRelease: 0.18,
      filterEnvAmt: 0.42,
      attack: 0.01,
      decay: 0.14,
      sustain: 0.80,
      release: 0.14,
      glide: 0.08,
      volume: 0.94,
      lfoRate: 0.14,
      lfoDepth: 0.06,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.18,
    ),
  ),

  SynthPreset(
    name: 'FM Bell Lead',
    category: SynthPresetCategory.leads,
    description: 'Plucked FM bell — sine carrier with 1:1 modulator. DX7 style.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: 0.0,
      osc1Gain: 1.0,
      osc2On: true,
      osc2Wave: SynthWave.sine,
      osc2Detune: 0.0,       // 1:1 ratio — classic bell spectrum
      osc2Gain: 0.0,         // pure FM modulator
      osc2FmDepth: 0.52,
      osc3On: false,
      osc3Wave: SynthWave.sine,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.82,
      resonance: 0.10,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.00,
      filterRelease: 0.12,
      filterEnvAmt: 0.30,
      attack: 0.00,
      decay: 0.28,
      sustain: 0.00,
      release: 0.28,
      glide: 0.00,
      volume: 0.92,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.08,
    ),
  ),

  SynthPreset(
    name: 'Square Lead',
    category: SynthPresetCategory.leads,
    description: 'Hollow square wave lead — nasal and cutting.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: 0.0,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.saw,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.saw,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.66,
      resonance: 0.20,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.44,
      filterRelease: 0.16,
      filterEnvAmt: 0.36,
      attack: 0.01,
      decay: 0.12,
      sustain: 0.82,
      release: 0.14,
      glide: 0.10,
      volume: 0.93,
      lfoRate: 0.14,
      lfoDepth: 0.05,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.20,
    ),
  ),

  SynthPreset(
    name: 'Screech Lead',
    category: SynthPresetCategory.leads,
    description: 'Aggressive resonant saw — high overtones with grit.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.0,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.saw,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.saw,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.74,
      resonance: 0.54,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.12,
      filterSustain: 0.50,
      filterRelease: 0.14,
      filterEnvAmt: 0.44,
      attack: 0.00,
      decay: 0.10,
      sustain: 0.84,
      release: 0.14,
      glide: 0.08,
      volume: 0.92,
      lfoRate: 0.14,
      lfoDepth: 0.04,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.46,
    ),
  ),

  SynthPreset(
    name: 'Pluck Lead',
    category: SynthPresetCategory.leads,
    description: 'Short pulse pluck for arps and melodic stabs.',
    build: () => SimpleSynthParams(
      wave: SynthWave.pulse,
      detune: 0.0,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.saw,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.saw,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.68,
      resonance: 0.22,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.09,
      filterSustain: 0.00,
      filterRelease: 0.08,
      filterEnvAmt: 0.64,
      attack: 0.00,
      decay: 0.10,
      sustain: 0.00,
      release: 0.10,
      glide: 0.00,
      volume: 0.94,
      lfoRate: 0.14,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.16,
    ),
  ),

  // ── Drums additions ───────────────────────────────────────────────────────

  SynthPreset(
    name: '808 Kick',
    category: SynthPresetCategory.drums,
    description: 'Heavy 808-style kick — long sine body with drive.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: -0.88,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.sine,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.sine,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.38,
      resonance: 0.12,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.16,
      filterSustain: 0.00,
      filterRelease: 0.16,
      filterEnvAmt: 0.42,
      attack: 0.00,
      decay: 0.30,
      sustain: 0.00,
      release: 0.28,
      glide: 0.00,
      volume: 0.98,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.46,
    ),
  ),

  SynthPreset(
    name: 'Body Snare',
    category: SynthPresetCategory.drums,
    description: 'Noise snare with sine body layer — more punch and depth.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      osc1Gain: 0.80,
      osc2On: true,
      osc2Wave: SynthWave.sine,
      osc2Detune: -0.42,     // lower sine for body tone
      osc2Gain: 0.55,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.sine,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.78,
      resonance: 0.28,
      filterMode: SynthFilterMode.bandPass,
      filterAttack: 0.00,
      filterDecay: 0.10,
      filterSustain: 0.00,
      filterRelease: 0.10,
      filterEnvAmt: 0.46,
      attack: 0.00,
      decay: 0.13,
      sustain: 0.00,
      release: 0.12,
      glide: 0.00,
      volume: 0.96,
      lfoRate: 0.14,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.30,
    ),
  ),

  SynthPreset(
    name: 'Rim Shot',
    category: SynthPresetCategory.drums,
    description: 'Sharp percussive crack — tight noise for rim and accent hits.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.sine,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.sine,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.86,
      resonance: 0.40,
      filterMode: SynthFilterMode.bandPass,
      filterAttack: 0.00,
      filterDecay: 0.04,
      filterSustain: 0.00,
      filterRelease: 0.04,
      filterEnvAmt: 0.60,
      attack: 0.00,
      decay: 0.05,
      sustain: 0.00,
      release: 0.04,
      glide: 0.00,
      volume: 0.95,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.20,
    ),
  ),

  SynthPreset(
    name: 'Tom',
    category: SynthPresetCategory.drums,
    description: 'Tonal sine tom with filter sweep for pitch-drop character.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: -0.30,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.sine,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.sine,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.50,
      resonance: 0.18,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.00,
      filterRelease: 0.12,
      filterEnvAmt: 0.52,
      attack: 0.00,
      decay: 0.18,
      sustain: 0.00,
      release: 0.16,
      glide: 0.00,
      volume: 0.96,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.22,
    ),
  ),

  SynthPreset(
    name: 'FM Cowbell',
    category: SynthPresetCategory.drums,
    description: 'Metallic FM cowbell — square + inharmonic modulator at 3:2 ratio.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: 0.40,
      osc1Gain: 0.80,
      osc2On: true,
      osc2Wave: SynthWave.square,
      osc2Detune: 0.58,      // ~7 semitones ≈ 3:2 (inharmonic bell character)
      osc2Gain: 0.30,
      osc2FmDepth: 0.62,
      osc3On: false,
      osc3Wave: SynthWave.square,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.90,
      resonance: 0.20,
      filterMode: SynthFilterMode.highPass,
      filterAttack: 0.00,
      filterDecay: 0.08,
      filterSustain: 0.00,
      filterRelease: 0.08,
      filterEnvAmt: 0.20,
      attack: 0.00,
      decay: 0.18,
      sustain: 0.00,
      release: 0.18,
      glide: 0.00,
      volume: 0.92,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.30,
    ),
  ),

  SynthPreset(
    name: 'Clap',
    category: SynthPresetCategory.drums,
    description: 'Wide noise clap with slight room tail.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.noise,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.noise,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.82,
      resonance: 0.20,
      filterMode: SynthFilterMode.bandPass,
      filterAttack: 0.00,
      filterDecay: 0.08,
      filterSustain: 0.00,
      filterRelease: 0.14,
      filterEnvAmt: 0.38,
      attack: 0.00,
      decay: 0.08,
      sustain: 0.00,
      release: 0.22,
      glide: 0.00,
      volume: 0.96,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.18,
    ),
  ),

  // ── Pads additions ────────────────────────────────────────────────────────

  SynthPreset(
    name: 'FM Glass',
    category: SynthPresetCategory.pads,
    description: 'Glassy pad — sine carrier with subtle FM shimmer, slow bloom.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: 0.00,
      osc1Gain: 1.0,
      osc2On: true,
      osc2Wave: SynthWave.sine,
      osc2Detune: 0.0,       // 1:1 ratio adds upper partials
      osc2Gain: 0.25,
      osc2FmDepth: 0.12,
      osc3On: false,
      osc3Wave: SynthWave.sine,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.78,
      resonance: 0.12,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.28,
      filterDecay: 0.30,
      filterSustain: 0.60,
      filterRelease: 0.50,
      filterEnvAmt: 0.20,
      attack: 0.30,
      decay: 0.28,
      sustain: 0.76,
      release: 0.50,
      glide: 0.00,
      volume: 0.88,
      lfoRate: 0.14,
      lfoDepth: 0.03,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.06,
    ),
  ),

  SynthPreset(
    name: 'Soft Strings',
    category: SynthPresetCategory.pads,
    description: 'Detuned saw ensemble — two oscillators spread for warmth.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.03,
      osc1Gain: 0.75,
      osc2On: true,
      osc2Wave: SynthWave.saw,
      osc2Detune: -0.05,     // slight spread below carrier
      osc2Gain: 0.70,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.saw,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.56,
      resonance: 0.12,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.22,
      filterDecay: 0.30,
      filterSustain: 0.55,
      filterRelease: 0.44,
      filterEnvAmt: 0.22,
      attack: 0.22,
      decay: 0.28,
      sustain: 0.80,
      release: 0.44,
      glide: 0.00,
      volume: 0.90,
      lfoRate: 0.16,
      lfoDepth: 0.04,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.08,
    ),
  ),

  SynthPreset(
    name: 'Choir',
    category: SynthPresetCategory.pads,
    description: 'Hollow square choir — vocal-like pad for slow progressions.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: 0.02,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.square,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.square,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.50,
      resonance: 0.16,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.26,
      filterDecay: 0.32,
      filterSustain: 0.56,
      filterRelease: 0.48,
      filterEnvAmt: 0.18,
      attack: 0.24,
      decay: 0.28,
      sustain: 0.78,
      release: 0.48,
      glide: 0.00,
      volume: 0.88,
      lfoRate: 0.14,
      lfoDepth: 0.04,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.06,
    ),
  ),

  // ── FX ────────────────────────────────────────────────────────────────────

  SynthPreset(
    name: 'Laser',
    category: SynthPresetCategory.fx,
    description: 'Classic laser zap — fast LFO pitch wobble with sharp decay.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: 0.60,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.sine,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.sine,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.90,
      resonance: 0.10,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.08,
      filterSustain: 0.00,
      filterRelease: 0.08,
      filterEnvAmt: 0.20,
      attack: 0.00,
      decay: 0.10,
      sustain: 0.00,
      release: 0.10,
      glide: 0.00,
      volume: 0.92,
      lfoRate: 0.80,
      lfoDepth: 0.35,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.24,
    ),
  ),

  SynthPreset(
    name: 'FM Metal',
    category: SynthPresetCategory.fx,
    description: 'Inharmonic FM metallic hit — triangle + heavy FM, percussive.',
    build: () => SimpleSynthParams(
      wave: SynthWave.triangle,
      detune: 0.30,
      osc1Gain: 0.90,
      osc2On: true,
      osc2Wave: SynthWave.triangle,
      osc2Detune: 0.58,      // ~7 semitones ≈ 3:2 inharmonic ratio
      osc2Gain: 0.30,
      osc2FmDepth: 0.78,
      osc3On: false,
      osc3Wave: SynthWave.triangle,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.88,
      resonance: 0.16,
      filterMode: SynthFilterMode.highPass,
      filterAttack: 0.00,
      filterDecay: 0.10,
      filterSustain: 0.00,
      filterRelease: 0.10,
      filterEnvAmt: 0.18,
      attack: 0.00,
      decay: 0.20,
      sustain: 0.00,
      release: 0.18,
      glide: 0.00,
      volume: 0.90,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.34,
    ),
  ),

  SynthPreset(
    name: 'Riser',
    category: SynthPresetCategory.fx,
    description: 'Noise riser with slow LFO filter sweep — build-up effect.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      osc1Gain: 1.0,
      osc2On: false,
      osc2Wave: SynthWave.noise,
      osc2Detune: 0.0,
      osc2Gain: 0.0,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.noise,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.22,
      resonance: 0.30,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.20,
      filterSustain: 0.60,
      filterRelease: 0.30,
      filterEnvAmt: 0.20,
      attack: 0.30,
      decay: 0.20,
      sustain: 0.90,
      release: 0.20,
      glide: 0.00,
      volume: 0.88,
      lfoRate: 0.06,
      lfoDepth: 0.70,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.16,
    ),
  ),

  SynthPreset(
    name: 'FM Zap',
    category: SynthPresetCategory.fx,
    description: 'FM noise zap — triangle modulator adds metallic crack.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      osc1Gain: 0.70,
      osc2On: true,
      osc2Wave: SynthWave.triangle,
      osc2Detune: 0.50,
      osc2Gain: 0.0,         // pure FM modulator
      osc2FmDepth: 0.55,
      osc3On: false,
      osc3Wave: SynthWave.triangle,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.88,
      resonance: 0.18,
      filterMode: SynthFilterMode.highPass,
      filterAttack: 0.00,
      filterDecay: 0.06,
      filterSustain: 0.00,
      filterRelease: 0.06,
      filterEnvAmt: 0.28,
      attack: 0.00,
      decay: 0.07,
      sustain: 0.00,
      release: 0.06,
      glide: 0.00,
      volume: 0.90,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.28,
    ),
  ),

  SynthPreset(
    name: 'Drone',
    category: SynthPresetCategory.fx,
    description: 'Slow LFO detuned saw drone — sustained textural layer.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.02,
      osc1Gain: 0.80,
      osc2On: true,
      osc2Wave: SynthWave.saw,
      osc2Detune: -0.03,     // slight spread for thickness
      osc2Gain: 0.70,
      osc2FmDepth: 0.0,
      osc3On: false,
      osc3Wave: SynthWave.saw,
      osc3Detune: 0.0,
      osc3Gain: 0.0,
      osc3FmDepth: 0.0,
      cutoff: 0.44,
      resonance: 0.22,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.20,
      filterSustain: 0.80,
      filterRelease: 0.30,
      filterEnvAmt: 0.16,
      attack: 0.00,
      decay: 0.20,
      sustain: 0.94,
      release: 0.30,
      glide: 0.00,
      volume: 0.88,
      lfoRate: 0.08,
      lfoDepth: 0.22,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.12,
    ),
  ),
];

List<SynthPreset> factoryPresetsByCategory(SynthPresetCategory category) {
  return kFactorySynthPresets
      .where((p) => p.category == category)
      .toList(growable: false);
}
