import 'instrument_model.dart';

enum SynthPresetCategory {
  melody,
  keyboard,
  drums,
  pads,
}

extension SynthPresetCategoryLabel on SynthPresetCategory {
  String get label {
    switch (this) {
      case SynthPresetCategory.melody:
        return 'Melody';
      case SynthPresetCategory.keyboard:
        return 'Keyboard';
      case SynthPresetCategory.drums:
        return 'Drums';
      case SynthPresetCategory.pads:
        return 'Pads';
    }
  }
}

class SynthPreset {
  final String name;
  final SynthPresetCategory category;
  final String description;
  final SimpleSynthParams Function() build;

  const SynthPreset({
    required this.name,
    required this.category,
    required this.description,
    required this.build,
  });

  SimpleSynthParams createParams() => build();

  void applyTo(SimpleSynthParams target) {
    final p = build();
    target.wave = p.wave;
    target.detune = p.detune;
    target.cutoff = p.cutoff;
    target.resonance = p.resonance;
    target.filterMode = p.filterMode;
    target.filterAttack = p.filterAttack;
    target.filterDecay = p.filterDecay;
    target.filterSustain = p.filterSustain;
    target.filterRelease = p.filterRelease;
    target.filterEnvAmt = p.filterEnvAmt;
    target.attack = p.attack;
    target.decay = p.decay;
    target.sustain = p.sustain;
    target.release = p.release;
    target.glide = p.glide;
    target.volume = p.volume;
    target.lfoRate = p.lfoRate;
    target.lfoDepth = p.lfoDepth;
    target.lfoTarget = p.lfoTarget;
    target.drive = p.drive;
  }
}

final List<SynthPreset> kFactorySynthPresets = <SynthPreset>[
  SynthPreset(
    name: 'Default',
    category: SynthPresetCategory.melody,
    description: 'Solid all-round saw starting point.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.0,
      cutoff: 0.78,
      resonance: 0.16,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.18,
      filterSustain: 0.28,
      filterRelease: 0.18,
      filterEnvAmt: 0.40,
      attack: 0.00,
      decay: 0.16,
      sustain: 0.80,
      release: 0.16,
      glide: 0.00,
      volume: 0.92,
      lfoRate: 0.20,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.10,
    ),
  ),
  SynthPreset(
    name: 'Mono Bass',
    category: SynthPresetCategory.melody,
    description: 'Tight low-pass bass for simple lines.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: -0.06,
      cutoff: 0.34,
      resonance: 0.30,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.12,
      filterSustain: 0.10,
      filterRelease: 0.10,
      filterEnvAmt: 0.62,
      attack: 0.00,
      decay: 0.10,
      sustain: 0.84,
      release: 0.10,
      glide: 0.08,
      volume: 0.96,
      lfoRate: 0.16,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.22,
    ),
  ),
  SynthPreset(
    name: 'Deep Bass',
    category: SynthPresetCategory.melody,
    description: 'Rounder, heavier bass with more low-end weight.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: -0.10,
      cutoff: 0.28,
      resonance: 0.18,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.12,
      filterRelease: 0.12,
      filterEnvAmt: 0.48,
      attack: 0.00,
      decay: 0.12,
      sustain: 0.88,
      release: 0.12,
      glide: 0.05,
      volume: 0.98,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.18,
    ),
  ),
  SynthPreset(
    name: 'Solid Lead',
    category: SynthPresetCategory.melody,
    description: 'Straight saw lead that cuts without getting thin.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.01,
      cutoff: 0.72,
      resonance: 0.20,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.24,
      filterRelease: 0.14,
      filterEnvAmt: 0.36,
      attack: 0.00,
      decay: 0.12,
      sustain: 0.78,
      release: 0.14,
      glide: 0.03,
      volume: 0.94,
      lfoRate: 0.18,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.16,
    ),
  ),
  SynthPreset(
    name: 'Pulse Lead',
    category: SynthPresetCategory.melody,
    description: 'Classic pulse-style lead with a bit more bite.',
    build: () => SimpleSynthParams(
      wave: SynthWave.pulse,
      detune: 0.0,
      cutoff: 0.68,
      resonance: 0.26,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.10,
      filterSustain: 0.22,
      filterRelease: 0.12,
      filterEnvAmt: 0.46,
      attack: 0.00,
      decay: 0.10,
      sustain: 0.76,
      release: 0.14,
      glide: 0.00,
      volume: 0.93,
      lfoRate: 0.18,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.18,
    ),
  ),
  SynthPreset(
    name: 'Acid Mono',
    category: SynthPresetCategory.melody,
    description: 'Resonant mono line for sharper acidic phrases.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.0,
      cutoff: 0.40,
      resonance: 0.68,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.04,
      filterRelease: 0.10,
      filterEnvAmt: 0.82,
      attack: 0.00,
      decay: 0.10,
      sustain: 0.76,
      release: 0.10,
      glide: 0.14,
      volume: 0.94,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.30,
    ),
  ),
  SynthPreset(
    name: 'Soft Pluck',
    category: SynthPresetCategory.keyboard,
    description: 'Short pluck for arps and picked parts.',
    build: () => SimpleSynthParams(
      wave: SynthWave.pulse,
      detune: 0.0,
      cutoff: 0.60,
      resonance: 0.24,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.10,
      filterSustain: 0.00,
      filterRelease: 0.08,
      filterEnvAmt: 0.72,
      attack: 0.00,
      decay: 0.10,
      sustain: 0.08,
      release: 0.08,
      glide: 0.00,
      volume: 0.94,
      lfoRate: 0.16,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.12,
    ),
  ),
  SynthPreset(
    name: 'Soft Keys',
    category: SynthPresetCategory.keyboard,
    description: 'Round mellow keys for chords and simple riffs.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: 0.01,
      cutoff: 0.58,
      resonance: 0.14,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.02,
      filterDecay: 0.24,
      filterSustain: 0.30,
      filterRelease: 0.20,
      filterEnvAmt: 0.26,
      attack: 0.02,
      decay: 0.20,
      sustain: 0.70,
      release: 0.20,
      glide: 0.00,
      volume: 0.92,
      lfoRate: 0.14,
      lfoDepth: 0.02,
      lfoTarget: SynthLfoTarget.amp,
      drive: 0.08,
    ),
  ),
  SynthPreset(
    name: 'Bright Pluck',
    category: SynthPresetCategory.keyboard,
    description: 'Sharper pluck for arps and picked rhythmic parts.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: 0.01,
      cutoff: 0.72,
      resonance: 0.28,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.08,
      filterSustain: 0.00,
      filterRelease: 0.06,
      filterEnvAmt: 0.68,
      attack: 0.00,
      decay: 0.08,
      sustain: 0.10,
      release: 0.08,
      glide: 0.00,
      volume: 0.95,
      lfoRate: 0.14,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.amp,
      drive: 0.16,
    ),
  ),
  SynthPreset(
    name: 'Organ',
    category: SynthPresetCategory.keyboard,
    description: 'Simple bright organ for stabs and held chords.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: 0.00,
      cutoff: 0.88,
      resonance: 0.10,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.10,
      filterSustain: 0.84,
      filterRelease: 0.12,
      filterEnvAmt: 0.08,
      attack: 0.00,
      decay: 0.08,
      sustain: 0.92,
      release: 0.10,
      glide: 0.00,
      volume: 0.95,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.amp,
      drive: 0.20,
    ),
  ),
  SynthPreset(
    name: 'Kick',
    category: SynthPresetCategory.drums,
    description: 'Simple synth kick with punch and body.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: -0.78,
      cutoff: 0.42,
      resonance: 0.16,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.08,
      filterSustain: 0.00,
      filterRelease: 0.08,
      filterEnvAmt: 0.34,
      attack: 0.00,
      decay: 0.12,
      sustain: 0.00,
      release: 0.10,
      glide: 0.00,
      volume: 0.98,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.26,
    ),
  ),
  SynthPreset(
    name: 'Snare',
    category: SynthPresetCategory.drums,
    description: 'Noise snare with a short bright crack.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      cutoff: 0.76,
      resonance: 0.32,
      filterMode: SynthFilterMode.bandPass,
      filterAttack: 0.00,
      filterDecay: 0.10,
      filterSustain: 0.00,
      filterRelease: 0.10,
      filterEnvAmt: 0.50,
      attack: 0.00,
      decay: 0.11,
      sustain: 0.00,
      release: 0.10,
      glide: 0.00,
      volume: 0.96,
      lfoRate: 0.14,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.24,
    ),
  ),
  SynthPreset(
    name: 'Hat',
    category: SynthPresetCategory.drums,
    description: 'Short bright hat for simple patterns.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      cutoff: 0.92,
      resonance: 0.14,
      filterMode: SynthFilterMode.highPass,
      filterAttack: 0.00,
      filterDecay: 0.04,
      filterSustain: 0.00,
      filterRelease: 0.04,
      filterEnvAmt: 0.12,
      attack: 0.00,
      decay: 0.05,
      sustain: 0.00,
      release: 0.04,
      glide: 0.00,
      volume: 0.94,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.12,
    ),
  ),
  SynthPreset(
    name: 'Open Hat',
    category: SynthPresetCategory.drums,
    description: 'Longer brighter hat tail for open accents.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      cutoff: 0.94,
      resonance: 0.16,
      filterMode: SynthFilterMode.highPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.00,
      filterRelease: 0.20,
      filterEnvAmt: 0.10,
      attack: 0.00,
      decay: 0.16,
      sustain: 0.00,
      release: 0.22,
      glide: 0.00,
      volume: 0.94,
      lfoRate: 0.12,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.10,
    ),
  ),
  SynthPreset(
    name: 'Warm Pad',
    category: SynthPresetCategory.pads,
    description: 'Slow soft pad for sustained harmony.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.03,
      cutoff: 0.52,
      resonance: 0.14,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.18,
      filterDecay: 0.28,
      filterSustain: 0.52,
      filterRelease: 0.40,
      filterEnvAmt: 0.24,
      attack: 0.18,
      decay: 0.30,
      sustain: 0.78,
      release: 0.46,
      glide: 0.00,
      volume: 0.90,
      lfoRate: 0.16,
      lfoDepth: 0.05,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.08,
    ),
  ),
  SynthPreset(
    name: 'Bright Pad',
    category: SynthPresetCategory.pads,
    description: 'Brighter sustaining pad for upper parts.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.02,
      cutoff: 0.70,
      resonance: 0.18,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.14,
      filterDecay: 0.24,
      filterSustain: 0.60,
      filterRelease: 0.42,
      filterEnvAmt: 0.18,
      attack: 0.14,
      decay: 0.24,
      sustain: 0.80,
      release: 0.42,
      glide: 0.00,
      volume: 0.90,
      lfoRate: 0.18,
      lfoDepth: 0.04,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.10,
    ),
  ),
];

List<SynthPreset> factoryPresetsByCategory(SynthPresetCategory category) {
  return kFactorySynthPresets
      .where((p) => p.category == category)
      .toList(growable: false);
}
