import 'instrument_model.dart';

enum SynthPresetCategory {
  melody,
  keyboard,
  drums,
  pads,
}

extension SynthPresetCategoryLabel on SynthPresetCategory {
  String get label {
    switch (this) {
      case SynthPresetCategory.melody:
        return 'Melody';
      case SynthPresetCategory.keyboard:
        return 'Keyboard';
      case SynthPresetCategory.drums:
        return 'Drums';
      case SynthPresetCategory.pads:
        return 'Pads';
    }
  }
}

class SynthPreset {
  final String name;
  final SynthPresetCategory category;
  final String description;
  final SimpleSynthParams Function() build;

  const SynthPreset({
    required this.name,
    required this.category,
    required this.description,
    required this.build,
  });

  SimpleSynthParams createParams() => build();

  void applyTo(SimpleSynthParams target) {
    final p = build();
    target.wave = p.wave;
    target.detune = p.detune;
    target.cutoff = p.cutoff;
    target.resonance = p.resonance;
    target.filterMode = p.filterMode;
    target.filterAttack = p.filterAttack;
    target.filterDecay = p.filterDecay;
    target.filterSustain = p.filterSustain;
    target.filterRelease = p.filterRelease;
    target.filterEnvAmt = p.filterEnvAmt;
    target.attack = p.attack;
    target.decay = p.decay;
    target.sustain = p.sustain;
    target.release = p.release;
    target.glide = p.glide;
    target.volume = p.volume;
    target.lfoRate = p.lfoRate;
    target.lfoDepth = p.lfoDepth;
    target.lfoTarget = p.lfoTarget;
    target.drive = p.drive;
  }
}

final List<SynthPreset> kFactorySynthPresets = <SynthPreset>[
  SynthPreset(
    name: 'Default',
    category: SynthPresetCategory.melody,
    description: 'Tracker synth default settings.',
    build: () => SimpleSynthParams(),
  ),

  // Melody
  SynthPreset(
    name: 'Neon Lead',
    category: SynthPresetCategory.melody,
    description: 'Bright saw lead with a little movement.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.02,
      cutoff: 0.74,
      resonance: 0.23,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.01,
      filterDecay: 0.18,
      filterSustain: 0.18,
      filterRelease: 0.18,
      filterEnvAmt: 0.48,
      attack: 0.01,
      decay: 0.16,
      sustain: 0.72,
      release: 0.20,
      glide: 0.04,
      volume: 0.84,
      lfoRate: 0.32,
      lfoDepth: 0.07,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.14,
    ),
  ),
  SynthPreset(
    name: 'Square Hero',
    category: SynthPresetCategory.melody,
    description: 'Classic square lead for hooks.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: -0.01,
      cutoff: 0.66,
      resonance: 0.30,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.13,
      filterSustain: 0.22,
      filterRelease: 0.16,
      filterEnvAmt: 0.44,
      attack: 0.00,
      decay: 0.15,
      sustain: 0.68,
      release: 0.14,
      glide: 0.03,
      volume: 0.82,
      lfoRate: 0.28,
      lfoDepth: 0.04,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.12,
    ),
  ),
  SynthPreset(
    name: 'Glass Bell',
    category: SynthPresetCategory.melody,
    description: 'Plucky bell-like melody sound.',
    build: () => SimpleSynthParams(
      wave: SynthWave.triangle,
      detune: 0.0,
      cutoff: 0.57,
      resonance: 0.42,
      filterMode: SynthFilterMode.bandPass,
      filterAttack: 0.00,
      filterDecay: 0.24,
      filterSustain: 0.08,
      filterRelease: 0.25,
      filterEnvAmt: 0.52,
      attack: 0.00,
      decay: 0.20,
      sustain: 0.18,
      release: 0.22,
      glide: 0.00,
      volume: 0.80,
      lfoRate: 0.25,
      lfoDepth: 0.02,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.06,
    ),
  ),
  SynthPreset(
    name: 'Acid Bite',
    category: SynthPresetCategory.melody,
    description: 'Resonant mono line with attitude.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.0,
      cutoff: 0.45,
      resonance: 0.72,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.16,
      filterSustain: 0.05,
      filterRelease: 0.14,
      filterEnvAmt: 0.86,
      attack: 0.00,
      decay: 0.12,
      sustain: 0.72,
      release: 0.12,
      glide: 0.16,
      volume: 0.80,
      lfoRate: 0.22,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.34,
    ),
  ),

  // Keyboard
  SynthPreset(
    name: 'Soft Keys',
    category: SynthPresetCategory.keyboard,
    description: 'Warm keyboard tone for chords.',
    build: () => SimpleSynthParams(
      wave: SynthWave.triangle,
      detune: 0.01,
      cutoff: 0.62,
      resonance: 0.18,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.03,
      filterDecay: 0.36,
      filterSustain: 0.36,
      filterRelease: 0.28,
      filterEnvAmt: 0.30,
      attack: 0.02,
      decay: 0.28,
      sustain: 0.62,
      release: 0.24,
      glide: 0.00,
      volume: 0.82,
      lfoRate: 0.18,
      lfoDepth: 0.03,
      lfoTarget: SynthLfoTarget.amp,
      drive: 0.08,
    ),
  ),
  SynthPreset(
    name: 'House Organ',
    category: SynthPresetCategory.keyboard,
    description: 'Bright organ stab for rhythm chords.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: 0.00,
      cutoff: 0.83,
      resonance: 0.12,
      filterMode: SynthFilterMode.highPass,
      filterAttack: 0.00,
      filterDecay: 0.10,
      filterSustain: 0.80,
      filterRelease: 0.12,
      filterEnvAmt: 0.18,
      attack: 0.00,
      decay: 0.08,
      sustain: 0.88,
      release: 0.10,
      glide: 0.00,
      volume: 0.84,
      lfoRate: 0.18,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.amp,
      drive: 0.16,
    ),
  ),
  SynthPreset(
    name: 'EP Dream',
    category: SynthPresetCategory.keyboard,
    description: 'Electric-piano flavored pluck.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: 0.0,
      cutoff: 0.70,
      resonance: 0.22,
      filterMode: SynthFilterMode.bandPass,
      filterAttack: 0.00,
      filterDecay: 0.22,
      filterSustain: 0.20,
      filterRelease: 0.22,
      filterEnvAmt: 0.46,
      attack: 0.00,
      decay: 0.23,
      sustain: 0.34,
      release: 0.26,
      glide: 0.00,
      volume: 0.81,
      lfoRate: 0.31,
      lfoDepth: 0.04,
      lfoTarget: SynthLfoTarget.amp,
      drive: 0.10,
    ),
  ),
  SynthPreset(
    name: 'Pluck Keys',
    category: SynthPresetCategory.keyboard,
    description: 'Short attack keys for arps.',
    build: () => SimpleSynthParams(
      wave: SynthWave.pulse,
      detune: 0.0,
      cutoff: 0.63,
      resonance: 0.34,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.14,
      filterSustain: 0.00,
      filterRelease: 0.10,
      filterEnvAmt: 0.66,
      attack: 0.00,
      decay: 0.12,
      sustain: 0.12,
      release: 0.10,
      glide: 0.00,
      volume: 0.80,
      lfoRate: 0.24,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.20,
    ),
  ),

  // Drums (synth percussion)
  SynthPreset(
    name: 'BD Punch',
    category: SynthPresetCategory.drums,
    description: 'Synth kick with fast pitch snap.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: -0.72,
      cutoff: 0.44,
      resonance: 0.20,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.08,
      filterSustain: 0.00,
      filterRelease: 0.08,
      filterEnvAmt: 0.44,
      attack: 0.00,
      decay: 0.14,
      sustain: 0.00,
      release: 0.10,
      glide: 0.00,
      volume: 0.88,
      lfoRate: 0.16,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.36,
    ),
  ),
  SynthPreset(
    name: 'BD Boom',
    category: SynthPresetCategory.drums,
    description: 'Longer 808-style low kick.',
    build: () => SimpleSynthParams(
      wave: SynthWave.sine,
      detune: -0.80,
      cutoff: 0.35,
      resonance: 0.15,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.00,
      filterDecay: 0.18,
      filterSustain: 0.00,
      filterRelease: 0.22,
      filterEnvAmt: 0.32,
      attack: 0.00,
      decay: 0.20,
      sustain: 0.00,
      release: 0.24,
      glide: 0.00,
      volume: 0.90,
      lfoRate: 0.14,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.pitch,
      drive: 0.28,
    ),
  ),
  SynthPreset(
    name: 'Snare Snap',
    category: SynthPresetCategory.drums,
    description: 'Noise-based snare with crack.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      cutoff: 0.74,
      resonance: 0.38,
      filterMode: SynthFilterMode.bandPass,
      filterAttack: 0.00,
      filterDecay: 0.12,
      filterSustain: 0.00,
      filterRelease: 0.10,
      filterEnvAmt: 0.58,
      attack: 0.00,
      decay: 0.12,
      sustain: 0.00,
      release: 0.10,
      glide: 0.00,
      volume: 0.84,
      lfoRate: 0.16,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.30,
    ),
  ),
  SynthPreset(
    name: 'Snare Body',
    category: SynthPresetCategory.drums,
    description: 'Rounder snare with more low mid.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: -0.10,
      cutoff: 0.58,
      resonance: 0.26,
      filterMode: SynthFilterMode.bandPass,
      filterAttack: 0.00,
      filterDecay: 0.16,
      filterSustain: 0.00,
      filterRelease: 0.16,
      filterEnvAmt: 0.40,
      attack: 0.00,
      decay: 0.16,
      sustain: 0.00,
      release: 0.14,
      glide: 0.00,
      volume: 0.82,
      lfoRate: 0.16,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.22,
    ),
  ),
  SynthPreset(
    name: 'Hat Closed',
    category: SynthPresetCategory.drums,
    description: 'Short bright closed hat.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      cutoff: 0.90,
      resonance: 0.16,
      filterMode: SynthFilterMode.highPass,
      filterAttack: 0.00,
      filterDecay: 0.04,
      filterSustain: 0.00,
      filterRelease: 0.04,
      filterEnvAmt: 0.20,
      attack: 0.00,
      decay: 0.05,
      sustain: 0.00,
      release: 0.04,
      glide: 0.00,
      volume: 0.78,
      lfoRate: 0.20,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.18,
    ),
  ),
  SynthPreset(
    name: 'Hat Open',
    category: SynthPresetCategory.drums,
    description: 'Longer open hat tail.',
    build: () => SimpleSynthParams(
      wave: SynthWave.noise,
      detune: 0.00,
      cutoff: 0.92,
      resonance: 0.18,
      filterMode: SynthFilterMode.highPass,
      filterAttack: 0.00,
      filterDecay: 0.16,
      filterSustain: 0.00,
      filterRelease: 0.22,
      filterEnvAmt: 0.16,
      attack: 0.00,
      decay: 0.22,
      sustain: 0.00,
      release: 0.28,
      glide: 0.00,
      volume: 0.76,
      lfoRate: 0.20,
      lfoDepth: 0.00,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.16,
    ),
  ),

  // Pads
  SynthPreset(
    name: 'Warm Pad',
    category: SynthPresetCategory.pads,
    description: 'Soft low-pass pad for chords.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.03,
      cutoff: 0.56,
      resonance: 0.18,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.22,
      filterDecay: 0.38,
      filterSustain: 0.58,
      filterRelease: 0.46,
      filterEnvAmt: 0.34,
      attack: 0.20,
      decay: 0.38,
      sustain: 0.74,
      release: 0.52,
      glide: 0.00,
      volume: 0.80,
      lfoRate: 0.24,
      lfoDepth: 0.09,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.08,
    ),
  ),
  SynthPreset(
    name: 'Air Choir',
    category: SynthPresetCategory.pads,
    description: 'Wide airy pad with filter movement.',
    build: () => SimpleSynthParams(
      wave: SynthWave.triangle,
      detune: 0.02,
      cutoff: 0.66,
      resonance: 0.22,
      filterMode: SynthFilterMode.bandPass,
      filterAttack: 0.25,
      filterDecay: 0.35,
      filterSustain: 0.54,
      filterRelease: 0.54,
      filterEnvAmt: 0.26,
      attack: 0.26,
      decay: 0.34,
      sustain: 0.72,
      release: 0.58,
      glide: 0.00,
      volume: 0.78,
      lfoRate: 0.18,
      lfoDepth: 0.12,
      lfoTarget: SynthLfoTarget.amp,
      drive: 0.06,
    ),
  ),
  SynthPreset(
    name: 'Dark Drift',
    category: SynthPresetCategory.pads,
    description: 'Moody darker pad with slow tremolo.',
    build: () => SimpleSynthParams(
      wave: SynthWave.square,
      detune: -0.01,
      cutoff: 0.46,
      resonance: 0.24,
      filterMode: SynthFilterMode.lowPass,
      filterAttack: 0.18,
      filterDecay: 0.30,
      filterSustain: 0.50,
      filterRelease: 0.48,
      filterEnvAmt: 0.24,
      attack: 0.22,
      decay: 0.30,
      sustain: 0.70,
      release: 0.56,
      glide: 0.00,
      volume: 0.76,
      lfoRate: 0.12,
      lfoDepth: 0.16,
      lfoTarget: SynthLfoTarget.amp,
      drive: 0.10,
    ),
  ),
  SynthPreset(
    name: 'Shimmer Pad',
    category: SynthPresetCategory.pads,
    description: 'Brighter pad for upper register.',
    build: () => SimpleSynthParams(
      wave: SynthWave.saw,
      detune: 0.04,
      cutoff: 0.74,
      resonance: 0.20,
      filterMode: SynthFilterMode.highPass,
      filterAttack: 0.16,
      filterDecay: 0.28,
      filterSustain: 0.62,
      filterRelease: 0.50,
      filterEnvAmt: 0.20,
      attack: 0.18,
      decay: 0.28,
      sustain: 0.76,
      release: 0.52,
      glide: 0.00,
      volume: 0.78,
      lfoRate: 0.26,
      lfoDepth: 0.10,
      lfoTarget: SynthLfoTarget.filter,
      drive: 0.09,
    ),
  ),
];

List<SynthPreset> factoryPresetsByCategory(SynthPresetCategory category) {
  return kFactorySynthPresets
      .where((p) => p.category == category)
      .toList(growable: false);
}
